#!/bin/busybox sh

rescue_shell() {
    echo "Something went wrong. Dropping to a shell."
    exec /bin/busybox sh
}

/bin/busybox mount -t devtmpfs none /dev
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sys /sys

/bin/busybox mdev -s

retry=10
until [ -b /dev/mmcblk0p1 -o $retry -gt 0 ]; do
  /bin/busybox sleep 1
  retry=$(($retry-1))
done

/bin/busybox mkdir /boot
/bin/busybox mount /dev/mmcblk0p1 /boot || rescue_shell

/bin/busybox mkdir /new_root
/bin/busybox mount -o ro,loop -t squashfs /boot/rootfs.squashfs /new_root || rescue_shell

/bin/busybox mount --move /dev /new_root/dev
/bin/busybox mount --move /proc /new_root/proc
/bin/busybox mount --move /sys /new_root/sys
/bin/busybox mount --move /boot /new_root/boot

exec /bin/busybox switch_root /new_root /usr/sbin/init || rescue_shell
