#!/bin/sh

case "$1" in
    start)
      retry=30

      while [ $retry -ge 0 ]; do
        wget -q -T 5 -O /dev/null http://google.com/ && break
        sleep 5
        retry=$(($retry-1))
      done

        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac


exit 0

