# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::423861535915:role/FridgeGithubAction
          role-session-name: GithubAction
          aws-region: us-east-1

      - name: Configure
        working-directory: buildroot
        run: make O=../4 BR2_EXTERNAL=../fridge rpi4_fridge_defconfig
        
      - name: Download sources
        working-directory: "4"
        run: make source -j 8

      - name: Cache sources
        run: aws s3 sync --exclude '*/.lock' buildroot/dl/ s3://fridge-build/dl/

      - name: Build
        working-directory: "4"
        run: make
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: fridge-rpi4
          path: 4/images
          
