# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure
        working-directory: buildroot
        run: make O=../4 BR2_EXTERNAL=../fridge rpi4_fridge_defconfig
        
      - name: Download sources
        working-directory: "4"
        run: make source
      
      - name: Cache sources
        run: az storage sync --account-name fridgebuild -c cache -s buildroot/dl -d dl

      - name: Build
        working-directory: "4"
        run: make
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: fridge-rpi4
          path: 4/images
          
