# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Restore ccache
        run: curl -L "https://fridge-build.s3.us-east-1.amazonaws.com/ccache.tar.zst" | tar -x --zst
        continue-on-error: true

      - name: Configure
        working-directory: buildroot
        run: make O=../4 BR2_EXTERNAL=../external rpi4_fridge_defconfig
        
      - name: Build
        working-directory: "4"
        run: make
      
      - name: Prepare Artifact
        run: |
          mv 4/images/rpi-firmware/* 4/images/
          cp boot/cmdline.txt boot/config.txt 4/images/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: fridge-rpi4
          path: 4/images
          
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::423861535915:role/FridgeGithubAction
          role-session-name: GithubAction
          aws-region: us-east-1

      - name: Cache sources
        run: aws s3 sync --exclude '*/.lock' --size-only buildroot/dl/ s3://fridge-build/dl/

      - name: Store ccache
        run: tar -cR --zst 4/ccache | aws s3 cp - s3://fridge-build/ccache.tar.zst
